[package]
name = "arn_os"
version = "0.1.0"
authors = ["Arnaud Tournier <ltearno@gmail.com>"]
edition = "2018"

[dependencies]
uart_16550 = "0.2.0"
spin = "0.4.9"
x86_64 = "0.7.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]